// GENERATED by scripts/prerender.py. Do not edit by hand.
// document.title for in-app navigation, matching the pre-rendered <title>.
export const PAGE_TITLES = {
  "/": "StockSaathi: Free Stock Market Simulator for Indian Teens",
  "/stocks": "Stock Market Simulator: 4,000+ NSE & BSE Stocks | StockSaathi",
  "/crash-replay": "Stock Market Crash Simulator: Replay Indian Crashes | StockSaathi",
  "/crash-replay/COVID_2020": "COVID-19 Crash (2020) Replay: Hold or Panic-Sell? | StockSaathi",
  "/crash-replay/GFC_2008": "Global Financial Crisis (2008) Replay: Hold or Panic-Sell? | StockSaathi",
  "/crash-replay/DEMO_2016": "Demonetisation Shock (2016) Replay: Hold or Panic-Sell? | StockSaathi",
  "/chat": "Ask Saathi: Free AI Stock Market Coach for Beginners | StockSaathi",
  "/news": "Indian Stock Market News with Sentiment | StockSaathi",
  "/learn-stock-market": "How to Learn the Stock Market as a Teenager in India",
  "/for-students": "Free Stock Market Simulator for Students in India | StockSaathi",
  "/compare/devion": "StockSaathi vs Devion: An Honest Comparison"
};
