// =============================================================================
// STATIC PAGE — content pages that exist only as pre-rendered HTML
// (/learn-stock-market, /for-students, /compare/devion; generated by
// scripts/prerender.py from partials/pages/*.html).
//
// On a cold load the server already sent the page, so the router keeps the
// markup it found in <main>. On in-app navigation we fetch the same URL and
// lift its <main> — one source of truth, no second copy of the text in JS.
// =============================================================================

let boot = null;              // { path, html } captured before the first render
const cache = new Map();      // path -> main innerHTML

export function captureBootMain(main) {
  if (boot || !main) return;
  boot = { path: location.pathname.replace(/\/+$/, "") || "/", html: main.innerHTML };
}

function currentPath() {
  return location.pathname.replace(/\/+$/, "") || "/";
}

export function renderStaticPage(main) {
  const path = currentPath();
  if (boot && boot.path === path && boot.html.includes(`data-static-page="${path}"`)) {
    main.innerHTML = boot.html;
    cache.set(path, boot.html);
    return;
  }
  if (cache.has(path)) {
    main.innerHTML = cache.get(path);
    return;
  }
  main.innerHTML = `<div class="empty-state" style="padding-top: var(--sp-12);">
    <div class="spinner" aria-hidden="true" style="margin: 0 auto var(--sp-4);"></div></div>`;
  fetch(path, { headers: { Accept: "text/html" } })
    .then(r => (r.ok ? r.text() : Promise.reject(new Error("http_" + r.status))))
    .then(text => {
      const doc = new DOMParser().parseFromString(text, "text/html");
      const html = doc.getElementById("main")?.innerHTML || "";
      if (!html.includes("data-static-page")) throw new Error("not_a_static_page");
      cache.set(path, html);
      if (currentPath() === path) main.innerHTML = html;   // user may have moved on
    })
    .catch(() => {
      // Hard navigation is always correct: the server has the page.
      if (currentPath() === path) location.reload();
    });
}
