// =============================================================================
// TERMS OF USE — Static legal page. Route: /terms. Public.
// =============================================================================

export function renderTerms(main) {
  main.innerHTML = `
    <div style="max-width: 820px; margin: 0 auto;">
      <h1>Terms of Use</h1>
      <p class="muted" style="margin: var(--sp-2) 0 var(--sp-5);">
        Last updated: 23 April 2026 &middot; Effective immediately.
      </p>

      <div class="card" style="margin-bottom: var(--sp-4); background: var(--bg-soft);">
        <p class="text-sm" style="line-height: 1.75;">
          <strong>Read this first.</strong> StockSaathi is an <strong>educational
          paper-trading simulator</strong>. Every number, portfolio,
          transfer and balance you see on the service is simulated. No real securities
          are bought, sold, or held. No real money is ever debited, credited, or held
          on your behalf. StockSaathi is <strong>not a SEBI-registered broker, investment
          adviser, research analyst, or portfolio manager</strong>, and is not affiliated
          with SEBI, NSE, BSE, or any broker. By using this service you agree to these
          terms.
        </p>
      </div>

      <div class="card" style="margin-bottom: var(--sp-4);">
        <h3 style="margin-bottom: var(--sp-3);">1. What StockSaathi is</h3>
        <p class="text-sm" style="line-height: 1.75;">
          StockSaathi is a web application that simulates the experience of investing
          in Indian equities and mutual funds using virtual money. Its purpose is
          educational. Coach responses are generated by an AI language model and are
          <strong>not</strong> investment advice, a recommendation to buy or sell any
          security, or a signal about future price movement.
        </p>
      </div>

      <div class="card" style="margin-bottom: var(--sp-4);">
        <h3 style="margin-bottom: var(--sp-3);">2. Eligibility</h3>
        <p class="text-sm" style="line-height: 1.75;">
          StockSaathi is intended for users aged 13 or older who understand that the
          service is educational and non-advisory. By registering you confirm that you
          meet this requirement.
        </p>
      </div>

      <div class="card" style="margin-bottom: var(--sp-4);">
        <h3 style="margin-bottom: var(--sp-3);">3. No investment advice, no securities activity</h3>
        <p class="text-sm" style="line-height: 1.75;">
          Nothing displayed on StockSaathi &mdash; quotes, charts, coach replies,
          news summaries, crash replays &mdash; constitutes investment advice,
          research, a solicitation to transact, or a recommendation to buy or sell any
          security. You are solely responsible for any real-world financial decision you
          make. Consult a SEBI-registered financial adviser before you commit real money
          to any instrument.
        </p>
      </div>

      <div class="card" style="margin-bottom: var(--sp-4);">
        <h3 style="margin-bottom: var(--sp-3);">4. Price data disclaimer</h3>
        <p class="text-sm" style="line-height: 1.75;">
          Price data displayed in the service is sourced from publicly accessible feeds
          (such as Yahoo Finance, CoinGecko, AMFI / MFAPI). StockSaathi does not hold an
          exchange data licence and does not guarantee the accuracy, completeness, or
          timeliness of the data. The data is displayed for educational illustration only.
          Users are <strong>not</strong> covered by SEBI&rsquo;s investor protection,
          grievance redressal, or dispute resolution mechanisms (including SCORES) for any
          activity on StockSaathi.
        </p>
      </div>

      <div class="card" style="margin-bottom: var(--sp-4);">
        <h3 style="margin-bottom: var(--sp-3);">5. Virtual currency and transfers</h3>
        <p class="text-sm" style="line-height: 1.75;">
          The &ldquo;cash&rdquo; shown in your account is a fictional in-app balance. Transfers
          between users are entries in our database and have no real-world monetary value.
          You cannot withdraw virtual cash or convert it into anything of value. No
          gambling, wagering, or prize scheme is operated on the service.
        </p>
      </div>

      <div class="card" style="margin-bottom: var(--sp-4);">
        <h3 style="margin-bottom: var(--sp-3);">6. Acceptable use</h3>
        <p class="text-sm" style="line-height: 1.75;">You will not:</p>
        <ul class="text-sm" style="line-height: 1.9; padding-left: var(--sp-5); margin: var(--sp-2) 0 0;">
          <li>Attempt to bypass the login, rate limits, or any security control.</li>
          <li>Impersonate another person, or create accounts using someone else&rsquo;s details.</li>
          <li>Upload content that is illegal, hateful, obscene, or that infringes a third party&rsquo;s rights.</li>
          <li>Scrape, reverse-engineer, or mirror the service beyond ordinary use.</li>
          <li>Treat the coach&rsquo;s output as advice, or repackage it as advice to someone else.</li>
          <li>Use the service to offer real-world trading, investment advisory, or money-transmission services.</li>
        </ul>
      </div>

      <div class="card" style="margin-bottom: var(--sp-4);">
        <h3 style="margin-bottom: var(--sp-3);">7. Intellectual property</h3>
        <p class="text-sm" style="line-height: 1.75;">
          The StockSaathi brand, design, code, and coach personality are our intellectual
          property. You keep ownership of content you post (e.g. your display name,
          profile bio). Stock names, ticker symbols, and price data belong to the
          respective exchanges and data vendors.
        </p>
      </div>

      <div class="card" style="margin-bottom: var(--sp-4);">
        <h3 style="margin-bottom: var(--sp-3);">8. Service availability</h3>
        <p class="text-sm" style="line-height: 1.75;">
          The service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. We
          may change, pause, or shut down any part of the service at any time. We are
          not obligated to retain data after account deletion beyond what our Privacy
          Policy states.
        </p>
      </div>

      <div class="card" style="margin-bottom: var(--sp-4);">
        <h3 style="margin-bottom: var(--sp-3);">9. Limitation of liability</h3>
        <p class="text-sm" style="line-height: 1.75;">
          To the maximum extent permitted by law, we are not liable for any loss,
          damage, claim, or demand arising from your use of the service, including but
          not limited to any real-world financial decision you made that was influenced
          by the service. You use the service at your own risk and agree that nothing
          displayed constitutes a recommendation or advice.
        </p>
      </div>

      <div class="card" style="margin-bottom: var(--sp-4);">
        <h3 style="margin-bottom: var(--sp-3);">10. Termination</h3>
        <p class="text-sm" style="line-height: 1.75;">
          You can delete your account at any time from Settings &rarr; Danger Zone. We may
          suspend or terminate access if you violate these terms or the Acceptable Use
          section.
        </p>
      </div>

      <div class="card" style="margin-bottom: var(--sp-4);">
        <h3 style="margin-bottom: var(--sp-3);">11. Governing law and disputes</h3>
        <p class="text-sm" style="line-height: 1.75;">
          These terms are governed by the laws of India. Any dispute that cannot be
          resolved through the grievance officer will be subject to the exclusive
          jurisdiction of the courts at the user&rsquo;s place of residence within India.
        </p>
      </div>

      <div class="card" style="margin-bottom: var(--sp-4);">
        <h3 style="margin-bottom: var(--sp-3);">12. Changes to these terms</h3>
        <p class="text-sm" style="line-height: 1.75;">
          We may update these terms occasionally. Material changes will be highlighted
          on this page and, where appropriate, surfaced in-app. Continued use of the
          service after a change means you accept the revised terms.
        </p>
      </div>

      <div class="flex gap-3" style="margin: var(--sp-6) 0 var(--sp-8); flex-wrap: wrap;">
        <a href="/privacy" class="btn btn-ghost">Privacy Policy</a>
        <a href="/grievance" class="btn btn-ghost">Grievance contact</a>
        <a href="/" class="btn btn-ghost">Back home</a>
      </div>
    </div>
  `;
}
