#!/usr/bin/env python3
"""
Build the landing page from partials/landing.html (the single source).

Writes:
  index.html                      markup between <!-- landing:start/end -->
                                  (logged-out CTA baked in, for crawlers and
                                  first paint), and the FAQPage JSON-LD
                                  between <!-- faq-jsonld:start/end -->.
  js/pages/landingContent.js      LANDING_HTML string for renderLanding().

The JSON-LD answers are derived from the visible .faq-item blocks, so the
structured data always says exactly what the page says.

Usage:  python scripts/build_landing.py [--check]
  --check  exit 1 if any output is out of date (use before committing).
Stdlib only.
"""

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PARTIAL = ROOT / "partials" / "landing.html"
INDEX = ROOT / "index.html"
MODULE = ROOT / "js" / "pages" / "landingContent.js"

CTA_PLACEHOLDER = "<!--CTA-->"
# Logged-out variant — must match ctaRowHtml(false, false) in landing.js.
CTA_LOGGED_OUT = (
    '    <a href="/register" class="btn btn-primary btn-lg">Create free account →</a>\n'
    '    <a href="/stocks" class="btn btn-ghost btn-lg">Explore markets, no signup</a>'
)


def load_partial():
    src = PARTIAL.read_text(encoding="utf-8")
    src = re.sub(r"^\s*<!--.*?-->\s*", "", src, count=1, flags=re.S)   # header comment
    if src.count(CTA_PLACEHOLDER) != 1:
        raise SystemExit("partials/landing.html: need exactly one %s, found %d" % (CTA_PLACEHOLDER, src.count(CTA_PLACEHOLDER)))
    if "-->" in src.split(CTA_PLACEHOLDER)[0].split("<section", 1)[0]:
        raise SystemExit("partials/landing.html: stray comment text before the first <section>")
    return src.strip() + "\n"


def text_of(fragment):
    t = re.sub(r"<[^>]+>", "", fragment)
    t = html.unescape(t)
    return re.sub(r"\s+", " ", t).strip()


def faq_jsonld(src):
    items = re.findall(r'<div class="faq-item"[^>]*>\s*<h3>(.*?)</h3>\s*<p>(.*?)</p>\s*</div>', src, flags=re.S)
    if len(items) < 3:
        raise SystemExit("expected FAQ items in partials/landing.html, found %d" % len(items))
    data = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "@id": "https://stocksaathi.co.in/#faq",
        "mainEntity": [
            {"@type": "Question", "name": text_of(q),
             "acceptedAnswer": {"@type": "Answer", "text": text_of(a)}}
            for q, a in items
        ],
    }
    body = json.dumps(data, ensure_ascii=False, indent=2)
    return '  <script type="application/ld+json">\n' + body + "\n  </script>\n"


def splice(doc, start, end, content, name):
    pat = re.compile(r"(" + re.escape(start) + r"\n)(.*?)(\n?[ \t]*" + re.escape(end) + r")", re.S)
    if not pat.search(doc):
        raise SystemExit("index.html: markers for %s not found" % name)
    return pat.sub(lambda m: m.group(1) + content.rstrip("\n") + m.group(3), doc, count=1)


def main():
    check = "--check" in sys.argv
    src = load_partial()

    static_html = src.replace(CTA_PLACEHOLDER, CTA_LOGGED_OUT)
    indented = "\n".join(("    " + ln) if ln.strip() else "" for ln in static_html.splitlines())

    index_old = INDEX.read_text(encoding="utf-8")
    index_new = splice(index_old, "<!-- landing:start -->", "<!-- landing:end -->", indented, "landing")
    index_new = splice(index_new, "<!-- faq-jsonld:start -->", "<!-- faq-jsonld:end -->", faq_jsonld(src), "faq-jsonld")

    module_new = (
        "// GENERATED by scripts/build_landing.py from partials/landing.html.\n"
        "// Do not edit by hand: edit the partial and re-run the script.\n"
        "export const CTA_PLACEHOLDER = " + json.dumps(CTA_PLACEHOLDER) + ";\n"
        "export const LANDING_HTML = " + json.dumps(src, ensure_ascii=False) + ";\n"
    )
    module_old = MODULE.read_text(encoding="utf-8") if MODULE.exists() else ""

    def same(a, b):                      # git autocrlf may hand us CRLF copies
        return a.replace("\r\n", "\n") == b.replace("\r\n", "\n")
    stale = [p.name for p, old, new in ((INDEX, index_old, index_new), (MODULE, module_old, module_new)) if not same(old, new)]
    if check:
        if stale:
            print("out of date:", ", ".join(stale), "- run: python scripts/build_landing.py")
            sys.exit(1)
        print("landing outputs up to date")
        return
    INDEX.write_text(index_new, encoding="utf-8", newline="\n")
    MODULE.write_text(module_new, encoding="utf-8", newline="\n")
    print("wrote:", ", ".join(stale) or "nothing (already current)")


if __name__ == "__main__":
    main()
