"""Generate js/data/dipStats.js: real dip-recovery statistics.

    python scripts/build_dip_stats.py

For each symbol (and the Nifty 50) this fetches daily closes since SINCE from
Yahoo Finance and measures, for every dip bucket X (5/7/10/15/20%):

- A dip starts on the first close at least X% below the running peak.
- It recovers on the first later close at or above that peak.
- recoveryDays = trading days from the dip start to the recovery close.
- After a recovery the peak tracking restarts from the recovery close, so one
  long fall counts once per bucket, not once per day.
- Dips that have not recovered yet are counted separately (`open`), never
  folded into the median.

These are the numbers the panic-sell pause and the stock page show as
"median trading days to recovery". Re-run it every few months; it only
reads public prices and writes one file.
"""
import datetime as dt
import json
import statistics
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "js" / "data" / "dipStats.js"
SINCE = "2011-01-01"
BUCKETS = [5, 7, 10, 15, 20]
IST = dt.timezone(dt.timedelta(hours=5, minutes=30))

# Large, liquid NSE names beginners actually trade. Everything else falls
# back to the Nifty 50 figures (see lookupDip in js/data/dips.js). TMPV is
# left out on purpose: Yahoo gives it Tata Motors' pre-demerger history.
SYMBOLS = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "BHARTIARTL", "SBIN", "ITC", "LT",
    "HINDUNILVR", "AXISBANK", "KOTAKBANK", "BAJFINANCE", "HDFCLIFE", "SBILIFE", "HCLTECH",
    "WIPRO", "TECHM", "LTIM", "MARUTI", "TMCV", "M&M", "EICHERMOT", "BAJAJ-AUTO",
    "TATASTEEL", "JSWSTEEL", "HINDALCO", "COALINDIA", "ONGC", "NTPC", "POWERGRID",
    "NESTLEIND", "BRITANNIA", "DABUR", "TITAN", "ASIANPAINT", "SUNPHARMA", "DRREDDY",
    "CIPLA", "DIVISLAB", "ULTRACEMCO", "GRASIM", "ETERNAL", "PAYTM", "NYKAA", "POLICYBZR",
    "DMART", "ADANIENT", "ADANIPORTS", "IRCTC",
]


def closes(ticker):
    a = int(dt.datetime.fromisoformat(SINCE).replace(tzinfo=dt.timezone.utc).timestamp())
    b = int(time.time())
    url = ("https://query1.finance.yahoo.com/v8/finance/chart/%s?period1=%d&period2=%d&interval=1d"
           % (urllib.parse.quote(ticker), a, b))
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    for attempt in range(4):
        try:
            res = json.load(urllib.request.urlopen(req, timeout=30))["chart"]["result"][0]
            break
        except urllib.error.HTTPError as e:
            if e.code == 404:
                return []
            if attempt == 3:
                raise
            time.sleep(3 * (attempt + 1))
        except Exception:
            if attempt == 3:
                raise
            time.sleep(3 * (attempt + 1))
    out = []
    for t, c in zip(res.get("timestamp") or [], res["indicators"]["quote"][0]["close"]):
        if c:
            out.append((dt.datetime.fromtimestamp(t, IST).date().isoformat(), c))
    return out


def dips(series, pct):
    done, open_ = [], 0
    peak, start = None, None
    for i, (_, c) in enumerate(series):
        if peak is None or (start is None and c > peak):
            peak = c
            continue
        if start is None:
            if c <= peak * (1 - pct / 100):
                start = i
        elif c >= peak:
            done.append(i - start)
            peak, start = c, None
    if start is not None:
        open_ = 1
    return done, open_


def stats(series):
    out = {}
    for pct in BUCKETS:
        done, open_ = dips(series, pct)
        if not done:
            continue
        out[pct] = {
            "recoveryDays": int(round(statistics.median(done))),
            "sampleSize": len(done),
            "minRecoveryDays": min(done),
            "maxRecoveryDays": max(done),
            "open": open_,
        }
    return out


def main():
    data, first = {}, {}
    for sym in SYMBOLS:
        s = closes(sym + ".NS")
        if len(s) < 250:
            print("skip %s: only %d closes" % (sym, len(s)))
            continue
        data[sym], first[sym] = stats(s), s[0][0]
        print("%-10s %s  %s" % (sym, s[0][0], {k: (v["recoveryDays"], v["sampleSize"]) for k, v in data[sym].items()}))
        time.sleep(0.5)
    nifty = closes("^NSEI")
    composite = stats(nifty)
    print("NIFTY50    %s  %s" % (nifty[0][0], {k: (v["recoveryDays"], v["sampleSize"]) for k, v in composite.items()}))

    body = (
        "// GENERATED by scripts/build_dip_stats.py on %s. Do not edit by hand.\n"
        "// Real dip-recovery statistics from Yahoo Finance daily closes since %s\n"
        "// (or since listing, see DIP_SINCE). Definitions are in the script.\n\n"
        "export const DIP_SINCE = %s;\n\n"
        "export const DIPS = %s;\n\n"
        "export const NIFTY_COMPOSITE = %s;\n"
        % (dt.date.today().isoformat(), SINCE,
           json.dumps({**first, "NIFTY50": nifty[0][0]}, indent=2, sort_keys=True),
           json.dumps(data, indent=2, sort_keys=True), json.dumps(composite, indent=2))
    )
    OUT.write_bytes(body.encode("utf-8"))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
